### ISSUE TITLE
where's zima?

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#258] opened 2015-09-25 15:51 UTC
![screen shot 2015-09-25 at 11 51 31 am](https://cloud.githubusercontent.com/assets/10051544/10105272/cb0c0152-637b-11e5-975c-19eeb5b8985c.png)

**Comment by jayvachon** [comment] 2015-09-25 15:55
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/248

**Closed as completed** 2015-09-25 19:14 UTC
Labels: duplicate
