### ISSUE TITLE
End of cities show endless water, then placeholder

### ISSUE THREAD

**Issue by sophiecalhoun** [engagementgamelab/WorldBank-RBF#61] opened 2015-07-07 18:29 UTC
After going through any city and interacting with all characters, the game then scrolls infinitely past background images and then the placeholder background.

![screen shot 2015-07-07 at 2 26 40 pm](https://cloud.githubusercontent.com/assets/12464696/8553866/4f2aa3aa-24b4-11e5-8c70-0a9dd1ece3ec.png)

**Comment by jayvachon** [comment] 2015-07-07 22:54
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/52

**Closed as completed** 2015-08-11 15:56 UTC
Labels: duplicate
