### ISSUE TITLE
Midwife in Mile -- "Unlock" prompt missing

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#65] opened 2015-07-07 19:04 UTC
When you get to the "she is clearly still steamed about what happened" dialogue, it gives the player a blank unlocked prompt which is confusing.

**Comment by jayvachon** [comment] 2015-07-07 22:46
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/65

**Comment by jpailthorpe** [comment] 2015-08-03 22:24
fixed

**Closed as completed by jpailthorpe** 2015-08-03 22:24 UTC
Labels: duplicate
