### ISSUE TITLE
camera shouldn't go over so far

### ISSUE THREAD

**Issue by KhyraBell** [engagementgamelab/WorldBank-RBF#120] opened 2015-08-05 18:07 UTC
![screen shot 2015-08-05 at 2 07 23 pm](https://cloud.githubusercontent.com/assets/12432115/9093656/5465cf9c-3b7b-11e5-83da-e880930de5c7.png)

**Comment by jayvachon** [comment] 2015-08-05 22:22
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/42

**Closed as completed** 2015-08-11 15:56 UTC
Labels: duplicate
