### ISSUE TITLE
Interacting with Kibari Herder occasionally breaks game

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#66] opened 2015-07-07 19:24 UTC
1. Load game, travel to Crup, then on to Kibari.
2. Selecting the Herder (old man with cane) occasionally properly loads dialogue, but repeatedly and randomly when he is first selected, the character will be highlighted as though the player is interacting with them, but no dialogue box emerges and the player is stuck without a way to continue.

**Comment by esalling23** [comment] 2015-07-07 19:39
I think this is because the big red question marks are blocking the dialogue? Or is this a different issue?

**Comment by sophiecalhoun** [comment] 2015-07-07 19:47
Different issue! :ocean:

**Comment by jayvachon** [comment] 2015-07-08 20:38
how many interactions did you have when this was happening?

**Comment by jayvachon** [comment] 2015-07-13 21:53
closing because I can't replicate. please reopen if you're able to reproduce the glitch & give me as much info as you can!

**Closed as completed by jayvachon** 2015-07-13 21:53 UTC
