### ISSUE TITLE
Ambiguous Mr. Todd Unlock 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#60] opened 2015-07-07 18:29 UTC
1. Load game, journey to Crup and then to Kibari.
2. Approach Mr. Todd and start interaction, initial dialogue loads, as well as first dialogue option--"Best Medicine Man." 
3. After selecting the only dialogue option and the dialogue finishes, the dialogue box displays 'Unlocked' followed by nothing. Looking at the YAML file, it seems this unlocks another dialogue with the Clinician in Kibari, but the seemingly-empty "Unlocked" prompt is confusing without any context.

**Comment by jayvachon** [comment] 2015-07-13 21:55
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/65

**Comment by jpailthorpe** [comment] 2015-08-03 22:24
fixed

**Closed as completed by jpailthorpe** 2015-08-03 22:24 UTC
Labels: duplicate
